/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

import static igu.ScrPpal.idAlumnoFastest;
import java.util.LinkedList;
import java.util.List;
import logic.Alumno;
import logic.Config;
import logic.Controladora;
import logic.Cuestionario;
import logic.Examen;
/**
 *
 * @author acmmi
 */
public class ScrTest extends javax.swing.JFrame {
    //Obtener registro con la configuración.
    Config configBdd; 
    Controladora ctrl;
    Cuestionario cueBdd;
    List<Cuestionario> listaCuestionariosBdd = null;  // Aquí estarán solo los cuestionarios que nos interesan.
    /**
     * Creates new form ScrTest
     */
    public ScrTest() {
        ctrl       = new  Controladora();
        configBdd  = new  Config();
        cueBdd     = new  Cuestionario ();
        listaCuestionariosBdd = new LinkedList<Cuestionario>();
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelPrimerasPreguntas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ScrTestZonaPreguntasIzda = new javax.swing.JEditorPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        ScrTestZonaPreguntasDer = new javax.swing.JEditorPane();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox10 = new javax.swing.JComboBox<>();
        jComboBox9 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JBtnGrabar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\acmmi\\Downloads\\linea simple.png")); // NOI18N
        jLabel3.setText("jLabel1");

        jPanelPrimerasPreguntas.setBackground(new java.awt.Color(255, 255, 255));

        ScrTestZonaPreguntasIzda.setEditable(false);
        ScrTestZonaPreguntasIzda.setBorder(null);
        ScrTestZonaPreguntasIzda.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        ScrTestZonaPreguntasIzda.setAutoscrolls(false);
        jScrollPane1.setViewportView(ScrTestZonaPreguntasIzda);

        ScrTestZonaPreguntasDer.setEditable(false);
        ScrTestZonaPreguntasDer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ScrTestZonaPreguntasDer.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jScrollPane3.setViewportView(ScrTestZonaPreguntasDer);

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jComboBox4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jComboBox5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jComboBox10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        jComboBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox10ActionPerformed(evt);
            }
        });

        jComboBox9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        jComboBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox9ActionPerformed(evt);
            }
        });

        jComboBox8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        jComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });

        jComboBox7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });

        jComboBox6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPrimerasPreguntasLayout = new javax.swing.GroupLayout(jPanelPrimerasPreguntas);
        jPanelPrimerasPreguntas.setLayout(jPanelPrimerasPreguntasLayout);
        jPanelPrimerasPreguntasLayout.setHorizontalGroup(
            jPanelPrimerasPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrimerasPreguntasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelPrimerasPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelPrimerasPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 3066, Short.MAX_VALUE))
        );
        jPanelPrimerasPreguntasLayout.setVerticalGroup(
            jPanelPrimerasPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrimerasPreguntasLayout.createSequentialGroup()
                .addGroup(jPanelPrimerasPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrimerasPreguntasLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPrimerasPreguntasLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134)
                        .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126)
                        .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119)
                        .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelPrimerasPreguntasLayout.createSequentialGroup()
                .addGroup(jPanelPrimerasPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 2475, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Preguntas");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Respuestas");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Preguntas");

        JBtnGrabar.setIcon(new javax.swing.ImageIcon("C:\\Users\\acmmi\\Documents\\Docencia\\Java\\disquette pequeño.png")); // NOI18N
        JBtnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnGrabarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(294, 294, 294)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1374, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBtnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelPrimerasPreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(JBtnGrabar))
                .addGap(18, 18, 18)
                .addComponent(jPanelPrimerasPreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(452, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1569, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        List<Cuestionario> listaCuePont = new LinkedList<Cuestionario>(); //Contendrá Todos los cuestionarios.
         //Contendrá SOLO los que coincidan con el filtro del file CONFIG.
        String txtPont = ""; // Muestra en pantalla las preguntas del examen.
        int i = 1; // ntx
        // CONFIG. Obtener nº de preguntas del examen.
        configBdd = ctrl.buscaBddConfig();
        // Volcado de CUESTIONARIO bdd A memoria
        listaCuePont = ctrl.buscaListaPreguntasBdd(); 
        // Filtrar solo las que pertenecen al examen actual
        listaCuestionariosBdd = ctrl.volcadoCuestionarioAMemoria(configBdd, listaCuePont);
        //Mostrar perguntas por pantalla.
        for (Cuestionario x : listaCuestionariosBdd){
              txtPont = txtPont + "Pregunta.- (" + i + ").- " +(x.getEnunciadoPregunta()+".\n"+
                      "   Respuesta A.- " + x.getEnunciadoRespuestaA()+"\n"+ "   Respuesta B.- " + x.getEnunciadoRespuestaB()+"\n"+
                      "   Respuesta C.- " + x.getEnunciadoRespuestaC()+"\n"+ "   Respuesta D.- " + x.getEnunciadoRespuestaD()+"\n"+"\n");
              //System.out.println("indice " +  i + " - " + x.getNumOrden());
              if (i==5){
                  ScrTestZonaPreguntasIzda.setText(txtPont);
                  txtPont = "";
              } 
              i++;
        }
        if (i<6){
                  ScrTestZonaPreguntasIzda.setText(txtPont);
                  txtPont = "";
              } else {
                ScrTestZonaPreguntasDer.setText(txtPont);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox7ActionPerformed

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox8ActionPerformed

    private void jComboBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox9ActionPerformed

    private void jComboBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox10ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void JBtnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnGrabarActionPerformed
        Cuestionario cueAGrabar = new Cuestionario();
        Examen       exaAGrabar = new Examen();
        Alumno       aluAGrabar = new Alumno();
        int i=0; // ntx
        
        //************** Grabar CUESTIONARIOS ******************
        // Capturar las contestaciones de los alumnos y grabarlas en el bdd.
        configBdd.getConfigNumPreguntas();
        // for (Cuestionario x : listaCuestionariosBdd ) 
        for (i=0; i<listaCuestionariosBdd.size(); i++) {
            System.out.println("------- " + listaCuestionariosBdd.get(i).getNumOrden());
            cueAGrabar.setCueIdeExaCue(listaCuestionariosBdd.get(i).getCueIdeExaCue());
            cueAGrabar.setNumOrden(listaCuestionariosBdd.get(i).getNumOrden());
            cueAGrabar.setEnunciadoPregunta(listaCuestionariosBdd.get(i).getEnunciadoPregunta());
            cueAGrabar.setEnunciadoRespuestaA(listaCuestionariosBdd.get(i).getEnunciadoRespuestaA());
            cueAGrabar.setEnunciadoRespuestaB(listaCuestionariosBdd.get(i).getEnunciadoRespuestaB());
            cueAGrabar.setEnunciadoRespuestaC(listaCuestionariosBdd.get(i).getEnunciadoRespuestaC());
            cueAGrabar.setEnunciadoRespuestaD(listaCuestionariosBdd.get(i).getEnunciadoRespuestaD());
            cueAGrabar.setRespuestaCorrecta(listaCuestionariosBdd.get(i).getRespuestaCorrecta());
            cueAGrabar.setId_Alu(listaCuestionariosBdd.get(i).getId_Alu());
            cueAGrabar.setId_Alu(idAlumnoFastest); // debería alimentarlo el cuestgionario
            cueAGrabar.setExamCuestionario(exaAGrabar);
            
            switch ( listaCuestionariosBdd.get(i).getNumOrden()){
                case 1: cueAGrabar.setRespuestaDlAlumno ((String) jComboBox1.getSelectedItem()  ); 
                    break;
                case 2: cueAGrabar.setRespuestaDlAlumno ((String) jComboBox2.getSelectedItem()  ); 
                    break;
                case 3: cueAGrabar.setRespuestaDlAlumno ((String) jComboBox3.getSelectedItem()  ); 
                    break;
                case 4: cueAGrabar.setRespuestaDlAlumno ((String) jComboBox4.getSelectedItem()  ); 
                    break;
                case 5: cueAGrabar.setRespuestaDlAlumno ((String) jComboBox5.getSelectedItem()  ); 
                    break;
                case 6: cueAGrabar.setRespuestaDlAlumno ((String) jComboBox6.getSelectedItem()  ); 
                    break;
                 case 7: cueAGrabar.setRespuestaDlAlumno ((String) jComboBox7.getSelectedItem()  ); 
                    break;
                case 8: cueAGrabar.setRespuestaDlAlumno ((String) jComboBox8.getSelectedItem()  ); 
                    break;
                case 9: cueAGrabar.setRespuestaDlAlumno ((String) jComboBox9.getSelectedItem()  ); 
                    break;
                case 10: cueAGrabar.setRespuestaDlAlumno ((String) jComboBox10.getSelectedItem()  ); 
                    break;
                default:
                    break;
            }
           // ctrl.crearCuestionarios(cueAGrabar);
        }
        //****************** Grabar EXAMEN **************
        exaAGrabar.setExaIdeExaCue ( cueAGrabar.getCueIdeExaCue()   );
        exaAGrabar.setFechaExamen ( configBdd.getConfigFecha() );
        exaAGrabar.setFp1Fp2 ( configBdd.getConfigFP1FP2());
        exaAGrabar.setAsignatura ( configBdd.getConfigAsignatura());
        exaAGrabar.setDescripExamen(configBdd.getConfigDescripcionExamen());
        exaAGrabar.setCriterioCorreccion(configBdd.getConfigCriterioCorreccion());
        exaAGrabar.setNumPreguntas(configBdd.getConfigNumPreguntas());
        exaAGrabar.setPrimeraVezSPresenta("");
        exaAGrabar.setObservaciones(configBdd.getConfigObservaciones());
        exaAGrabar.setNotaObtenida(99);
        exaAGrabar.setExamenAlumno(aluAGrabar);
        // De ArrayList a LinKedList
        LinkedList<Cuestionario> listaCueDListALinked = new LinkedList<>();
        listaCueDListALinked.addAll(listaCuestionariosBdd);
        exaAGrabar.setListaCuestionarioRdo(listaCueDListALinked);
        ctrl.crearExamen(exaAGrabar);
        //********** Grabar ALUMNO *****************
        // Posicionarse en el alumno creado en la Bdd, tenemos su dni=idAlumnoFastest
        ctrl.buscarEnBddAlumno();
        // Asignarle al alumno la LinkedList de Examenes.
        
        //
        
        /*
        
        ScrPpal.setId_Alu
        Scr01email;
        System.out.println(ScrPpal.Scr01email);        
                aluFastest.setId_Alu(121312312);
        
        Registro ya grabado en pantalla inicial.
        hay k recuperar ese registro e informarle la list
        
    @OneToMany (mappedBy="examenAlumno")
    private LinkedList<Examen> listaExamenesAlumno;
        */
    }//GEN-LAST:event_JBtnGrabarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScrTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScrTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScrTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScrTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScrTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnGrabar;
    private javax.swing.JEditorPane ScrTestZonaPreguntasDer;
    private javax.swing.JEditorPane ScrTestZonaPreguntasIzda;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelPrimerasPreguntas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

    
}
