package igu;

import java.util.LinkedList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import logica.Examen;
import logica.Alumno;
import logica.Controladora;
 
public class ModificarIdentificacion extends javax.swing.JFrame {
    Controladora control = null;
    int id_examen;
    Examen exa; // Declaramos variable global
    
    public ModificarIdentificacion(int id_examen) {
        control = new Controladora();
        //this.id_examen = id_examen;
        initComponents(); //Crea la interface gráfica
        cargarDatos(id_examen);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtScNombre = new javax.swing.JTextField();
        txtScApellido2 = new javax.swing.JTextField();
        txtScApellido1 = new javax.swing.JTextField();
        txtScCurso = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtScObservaciones = new javax.swing.JTextArea();
        cmbPrimeraParticipacion = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        btnScLimpiar = new javax.swing.JButton();
        btnScGuardar = new javax.swing.JButton();
        btnScGoExamen = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtScEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Curso:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("1er Apellido:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("2nd Apellido:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Observaciones:");

        txtScNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtScNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtScNombreActionPerformed(evt);
            }
        });

        txtScApellido2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtScApellido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtScApellido2ActionPerformed(evt);
            }
        });

        txtScApellido1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtScApellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtScApellido1ActionPerformed(evt);
            }
        });

        txtScCurso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtScCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtScCursoActionPerformed(evt);
            }
        });

        txtScObservaciones.setColumns(20);
        txtScObservaciones.setRows(5);
        jScrollPane1.setViewportView(txtScObservaciones);

        cmbPrimeraParticipacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbPrimeraParticipacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Sí", "No", "" }));
        cmbPrimeraParticipacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPrimeraParticipacionActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("¿Primera vez que te presentas?");

        btnScLimpiar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnScLimpiar.setText("Limpiar");
        btnScLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScLimpiarActionPerformed(evt);
            }
        });

        btnScGuardar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnScGuardar.setText("Guardar cambios");
        btnScGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScGuardarActionPerformed(evt);
            }
        });

        btnScGoExamen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnScGoExamen.setText("Ir al examen");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Email:");

        txtScEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtScEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtScEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtScNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtScApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtScApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtScCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtScEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(219, 219, 219))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(cmbPrimeraParticipacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnScLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnScGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnScGoExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel3, jLabel4});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnScGoExamen, btnScLimpiar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtScNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtScApellido1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtScApellido2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtScCurso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtScEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPrimeraParticipacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnScGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnScLimpiar)
                    .addComponent(btnScGoExamen))
                .addGap(69, 69, 69))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Modificar tus datos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtScNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtScNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtScNombreActionPerformed

    private void txtScApellido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtScApellido2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtScApellido2ActionPerformed

    private void txtScApellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtScApellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtScApellido1ActionPerformed

    private void txtScCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtScCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtScCursoActionPerformed

    private void cmbPrimeraParticipacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPrimeraParticipacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPrimeraParticipacionActionPerformed

    private void btnScLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScLimpiarActionPerformed
        // TODO add your handling code here: TETO: MÉTODO PARA LIMPIAR
        // Ctrl+Espacio: Nos muestra las sugerencias
       txtScNombre.setText("");
       txtScApellido1.setText("");
       txtScApellido2.setText("");
       txtScCurso.setText("");
       txtScEmail.setText("");
       txtScObservaciones.setText("");
       cmbPrimeraParticipacion.setSelectedIndex(0);
    }//GEN-LAST:event_btnScLimpiarActionPerformed

    private void txtScEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtScEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtScEmailActionPerformed

    private void btnScGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScGuardarActionPerformed
        
               
        control.modificarExayAlu (exa, txtScNombre.getText(), txtScApellido1.getText(), 
                txtScApellido2.getText(), txtScCurso.getText(), txtScEmail.getText(),
                txtScObservaciones.getText(), (String) cmbPrimeraParticipacion.getSelectedItem());
                 
        
        // Llamamos a método mostrar mensaje por pantalla.
        control.mostrarAviso ("Se modificó correctamente", "Modificado con éxito", "Info" );
        
        
        
        
    }//GEN-LAST:event_btnScGuardarActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnScGoExamen;
    private javax.swing.JButton btnScGuardar;
    private javax.swing.JButton btnScLimpiar;
    private javax.swing.JComboBox<String> cmbPrimeraParticipacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtScApellido1;
    private javax.swing.JTextField txtScApellido2;
    private javax.swing.JTextField txtScCurso;
    private javax.swing.JTextField txtScEmail;
    private javax.swing.JTextField txtScNombre;
    private javax.swing.JTextArea txtScObservaciones;
    // End of variables declaration//GEN-END:variables

    private void cargarDatos(int id_examen) {
        
        //Esta exa la declaramos como global
       this.exa = control.traerExamen(id_examen);
        
       txtScNombre.setText(exa.getAlumnExamen().getNombreAlumno());
       txtScApellido1.setText(exa.getAlumnExamen().getPrimerApellido());
       txtScApellido2.setText(exa.getAlumnExamen().getSegundoApellido());
       txtScCurso.setText(exa.getAlumnExamen().getCursoAlumno());
       txtScEmail.setText(exa.getAlumnExamen().getEmailAlumno());
       txtScObservaciones.setText(exa.getAlumnExamen().getObservacionesAlumno());
       
       if (exa.getAlumnExamen().getPrimeraConvocatoriaAlumno().equals("Sí")){
            cmbPrimeraParticipacion.setSelectedIndex(1);
        } else {
           if (exa.getAlumnExamen().getPrimeraConvocatoriaAlumno().equals("No")){
               cmbPrimeraParticipacion.setSelectedIndex(2);
              } else {
               cmbPrimeraParticipacion.setSelectedIndex(2);
         }
        }
       }
} // End public class
